
version: '3'


services:
  nginx:
    build: ./config/nginx-production
    command: [nginx, '-g', 'daemon off;']
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
