version: '3'

services:
  db:
    image: postgres
    volumes:
      - datavolume:/var/lib/postgresql/data
  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/code
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web


volumes:
  datavolume:
