version: '3'

services:
  db:
    image: postgres
    volumes:
      - datavolume:/var/lib/postgresql/data
    networks:  # <-- here
      - db_network
    env_file:
      - ./secrets/databaseconfig
  nginx:
    build: ./config/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8000:80
      - 443:443
    volumes:
      - staticvolume:/collected-static
    networks:  # <-- here
      - nginx_network
    depends_on:
      - web
  web:
    build: .
    command: /start.sh
    volumes:
      - staticvolume:/collected-static
    depends_on:
      - db
    networks:  # <-- here
      - nginx_network
      - db_network
    expose:
      - 8000


networks:  # <-- and here
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
volumes:
  datavolume:
  staticvolume:
