version: '3'

services:
  db:
    image: postgres
    volumes:
      - datavolume:/var/lib/postgresql/data
  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  datavolume:
